joint_limits:
  joint_3:
    has_velocity_limits: true
    max_velocity: 2.618
    has_acceleration_limits: false
    max_acceleration: 0
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.618
    has_acceleration_limits: false
    max_acceleration: 0
  joint_1:
    has_velocity_limits: true
    max_velocity: 2.618
    has_acceleration_limits: false
    max_acceleration: 0
  joint_6:
    has_velocity_limits: true
    max_velocity: 7.854
    has_acceleration_limits: false
    max_acceleration: 0
  joint_5:
    has_velocity_limits: true
    max_velocity: 6.2832
    has_acceleration_limits: false
    max_acceleration: 0
  joint_4:
    has_velocity_limits: true
    max_velocity: 6.2832
    has_acceleration_limits: false
    max_acceleration: 0